import next from 'eslint-config-next';

// eslint-config-next v16 ships a native flat config — spread it directly
// (FlatCompat hits a circular-JSON crash with the @typescript-eslint plugin).
const config = [
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'coverage/**',
      'drizzle/**',
      'playwright-report/**',
      'test-results/**',
      '.pglite/**',
      'public/sw.js',
      'next-env.d.ts',
      // Generated by the Workflow SDK build.
      'app/.well-known/**',
    ],
  },
  ...next,
];

export default config;
